SELECT TOP 1000 [CORE_DATUM_TYPE_ID]
      ,[DATA_ITEM_NAME]
      ,[DATA_SOURCE]
      ,[NATIVE_MEASUREMENT_PLACE_NAME]
      ,[NATIVE_MEASUREMENT_PLACE_ID]
      ,[MEASUREMENT_PLACE_ID]
      ,[NET_FLOW_PLACE_ID]
      ,[PLACE_VERSION_ID]
      ,[MEASUREMENT_PLACE_AGGREGATION]
      ,[LOCATION]
      ,[MEASUREMENT_TYPE]
      ,[MEASUREMENT_VERSION]
      ,[FIRMNESS]
      ,[CALORIFIC_VALUE]
      ,[NATIVE_DIRECTION_NAME]
      ,[NATIVE_DIRECTION]
      ,[MEASURE]
      ,[NATIVE_UNIT]
      ,[REPORT_PLACE_NAME]
      ,[REPORT_PLACE_VERSION]
      ,[FROM_COUNTRY]
      ,[TO_COUNTRY]
      ,[DATA_RESOLUTION]
      ,[LEADING_ZERO]
      ,[DATE_UPDATED]
  FROM [Fundalytics].[ATTR].[TSO_FLOW_ITEM]
  WHERE [CORE_DATUM_TYPE_ID] > 50000000
  AND [CORE_DATUM_TYPE_ID] = 50000075


SELECT TOP 1000 [DATA_PROVIDER_MAPPING_ID]
      ,[DATA_PROVIDER_ID]
      ,[DATA_PROVIDER_ITEM_ID]
      ,[CORE_DATUM_TYPE_ID]
      ,[MAPPING_START_DATETIME_UTC]
      ,[MAPPING_END_DATETIME_UTC]
      ,[LAST_DATA_PROVIDER_UPDATE_UTC]
      ,[AUDIT_DT]
      ,[ERROR_FLAG]
      ,[ERROR_DESCRIPTION]
      ,[ERROR_DATETIME_UTC]
      ,[KEEP_ALL_VERSIONS]
      ,[DATA_PROVIDER_TIME]
  FROM [Fundalytics].[_CORE].[DATA_PROVIDER_MAPPING]
  WHERE [CORE_DATUM_TYPE_ID] = 50000075




SELECT TOP 1000 [CurveId]
      ,[CurveName]
      ,[TimezoneId]
      ,[PublishCurve]
      ,[ArchiveDuplicates]
      ,[CurveType]
      ,[LastMetadataUpdateDateUtc]
      ,[MetadataUpdateProcessing]
      ,[LastMetadataProcessedDateUtc]
      ,[CurveDataBuildDateUtc]
      ,[KeepDuplicates]
      ,[PreserveStagingData]
      ,[PreserveTimezone]
  FROM [PointConnect].[pointconnect].[Curve]
  WHERE [CurveId] = 107595045



SELECT TOP 1000 [CurveId]
      ,[CurveName]
      ,[TimezoneId]
      ,[PublishCurve]
      ,[ArchiveDuplicates]
      ,[CurveType]
      ,[LastMetadataUpdateDateUtc]
      ,[MetadataUpdateProcessing]
      ,[LastMetadataProcessedDateUtc]
      ,[CurveDataBuildDateUtc]
      ,[KeepDuplicates]
      ,[PreserveStagingData]
      ,[PreserveTimezone]
  FROM [PointConnect].[pointconnect].[Curve]
  WHERE [CurveId] = 107595045


SELECT TOP 1000 [CurveDataId]
      ,[CurveId]
      ,[ValueDate]
      ,[ValueDateUtc]
      ,[ForecastDate]
      ,[ForecastDateUtc]
      ,[Value]
      ,[UpdatedDateUtc]
      ,[RowUpdatedDateUtc]
  FROM [PointConnect].[pointconnect].[CurveData]
  WHERE [CurveId] = 107595045